module.exports = {
  PORT_JSON_SERVER: 3000,
  PORT_EXPRESS_GQL_APP: 4000,
  PORT_EXPRESS_MONGODB_APP: 5000,
  PORT_REACT_APP: 7777,
  URL_BASE_DEV: 'http://localhost:',
  MOMENT_TIME_FORMAT: 'MMMM Do YYYY, HH:mm:ss',
  MOMENT_TIME_FORMAT_CALENDAR: 'YYYY-MM-DD HH:mm:ss',
  MOMENT_TIME_DAILY_FORMAT: 'MMMM Do YYYY',
}
